version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - rating-service

  rating-service:
    build: ./rating-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development

  user-service:
    build: ./user-service
    ports:
      - "8080:8080"

  cart-service:
    build: ./cart-service
    ports:
      - "3001:3001"

  order-service:
    build: ./order-service
    ports:
      - "8000:8000"

  payment-service:
    build: ./payment-service
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - rating-service
      - user-service
      - cart-service
      - order-service
      - payment-service
    environment:
      - REACT_APP_PRODUCT_SERVICE_URL=http://product-service:5001
      - REACT_APP_RATING_SERVICE_URL=http://rating-service:5002
