apiVersion: v1
kind: Secret
metadata:
  name: prod-sa-token
  namespace: ecommerce-prod
  annotations:
    kubernetes.io/service-account.name: prod-sa
type: kubernetes.io/service-account-token
